### ISSUE TITLE
Error in asset pricing code

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-jax#125]
From the rules of vectorization it seems to me that we should have a reshaping of `g` in the definition of the operator `A`, as shown below.  And yet maybe it's not necessary.  @HumphreyYang or @shlff , could you please take a look?

If both work I prefer the version below, since it's more explicit.

Thanks to Pilar, Conor and Joaquín for bringing my attention to this.

```python
def A(g, sv_model, shapes):
    # Set up
    P, hc_grid, Q, hd_grid, R, z_grid, β, γ, bar_σ, μ_c, μ_d = sv_model
    I, J, K = shapes
    # Reshape and broadcast over (i, j, k, i', j', k')
    hc = np.reshape(hc_grid,     (I, 1, 1, 1,  1,  1))
    hd = np.reshape(hd_grid,     (1, J, 1, 1,  1,  1))
    z = np.reshape(z_grid,       (1, 1, K, 1,  1,  1))
    P = np.reshape(P,            (I, 1, 1, I,  1,  1))
    Q = np.reshape(Q,            (1, J, 1, 1,  J,  1))
    R = np.reshape(R,            (1, 1, K, 1,  1,  K))
    g = np.reshape(g,            (1, 1, 1, I,  J,  K))
    a = μ_d - γ * μ_c
    b = bar_σ**2 * (jnp.exp(2 * hd) + γ**2 * jnp.exp(2 * hc)) / 2
    κ = jnp.exp(a + (1 - γ) * z + b)
    A = β * κ * P * Q * R
    Ag = jnp.sum(A * g, axis=(3, 4, 5))
    return Ag
```

**Comment by jstac** [comment]
Thanks @sgcbayli024 and @pilarbarros

**Comment by shlff** [comment]
Thanks guys. This is an interesting observation. 

According to my study, the original code is correct since the arrays in the product ``A * g``follow the broadcasting rule, see [here](https://numpy.org/doc/1.20/user/theory.broadcasting.html#:~:text=The%20rule%20governing%20whether%20two,expressed%20in%20a%20single%20sentence.&text=In%20order%20to%20broadcast%2C%20the,of%20them%20must%20be%20one.) or [here](https://python-programming.quantecon.org/numpy.html?highlight=broadcasting#broadcasting).

Here is a simple illustration: https://gist.github.com/shlff/c09def39413dbabf42dcf4fe0d41ddfd#file-investigation-ipynb

From my understanding the difference is that 
- with ``g = np.reshape(g, (1, 1, 1, I,  J,  K))``, it is easier to read, debug and extend,
- without it, running the code requires a bit less memory.
